### ISSUE TITLE
Add option to remove comments when parsing CSS files as CSSStyleSheet

### ISSUE THREAD

**Issue by xiaotong-tong** [swiing/rollup-plugin-import-assertions#6]
I'm using rollup-plugin-import-assertions to parse CSS files as CSSStyleSheet, but I noticed that comments in the CSS files are included as strings in the resulting CSSStyleSheet object. However, even with terser, the resulting files still contain the comments.This increases the file size.

It would be great if there was an option to remove comments when parsing CSS files as CSSStyleSheet. This would make the resulting CSSStyleSheet object smaller.

Is it possible to add such an option to rollup-plugin-import-assertions?

Thank you!

**Comment by swiing** [comment]
The recommended way-forward would be to pre-process the css with a plugin in order to perform any desired manipulation (you may want to remove comments, others will want other type of minification).

[You may want to have a look at [rollup-plugin-styles](https://anidetrix.github.io/rollup-plugin-styles/) with the `emit` option. Or if you find other plugin, please let us know]

**Comment by xiaotong-tong** [comment]
> [You may want to have a look at [rollup-plugin-styles](https://anidetrix.github.io/rollup-plugin-styles/) with the `emit` option. Or if you find other plugin, please let us know]

Thank you for your response! I tried the solution you provided and it worked perfectly. I used the `rollup-plugin-styles` and `postcss-discard-comments` plugins to handle the comment information in the CSS files. 
Here's the code I used:
```
styles({
  mode: "emit",
  plugins: [
    discardComments({
      removeAll: true
    })
  ]
})
```

**Comment by swiing** [comment]
Wonderful 

closing as solved
